//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedGood
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ShortProductName { get; set; }
        public string ModelNo { get; set; }
        public string CellType { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string ShortColorCode { get; set; }
        public string Brand { get; set; }
        public string ShortBrandCode { get; set; }
        public string SAC { get; set; }
        public int GST { get; set; }
        public string UOM { get; set; }
        public Nullable<int> MIN { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> StockFreez { get; set; }
        public Nullable<int> SelfStock { get; set; }
        public string TRfSelf { get; set; }
        public Nullable<int> Rate { get; set; }
        public string StockType { get; set; }
        public string CustomerName { get; set; }
        public string IsMinMax { get; set; }
        public Nullable<int> Cid { get; set; }
    }
}
