//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSheet
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string SalesOrderNo { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Model { get; set; }
        public string CellType { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string Brand { get; set; }
        public int QtyToPro { get; set; }
        public string BomNo { get; set; }
        public int QtyInPieace { get; set; }
        public Nullable<int> TotalQty { get; set; }
    }
}
