//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatIssueSlip
    {
        public int Id { get; set; }
        public string MrsNo { get; set; }
        public string Job { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public string Type { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public Nullable<int> QtyInPiece { get; set; }
        public Nullable<int> BalanceQty { get; set; }
        public string DateCreated { get; set; }
        public string BomNo { get; set; }
        public Nullable<int> IssueQty { get; set; }
        public Nullable<int> ytd { get; set; }
    }
}
