//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatPlanning
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string BomNo { get; set; }
        public string Code { get; set; }
        public string MatName { get; set; }
        public string Type { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public int Qty { get; set; }
        public int QtyReq { get; set; }
        public Nullable<int> QtyInStock { get; set; }
        public string MrsNo { get; set; }
        public Nullable<int> MrsWastQty { get; set; }
        public Nullable<int> MrsReqWastQty { get; set; }
        public Nullable<int> MrsReqQty { get; set; }
        public Nullable<int> MrsBalanceQtyRequired { get; set; }
        public string SalesNo { get; set; }
        public Nullable<int> QtyToPurchase { get; set; }
        public Nullable<int> IsPoCreated { get; set; }
        public Nullable<int> WasteQty { get; set; }
        public Nullable<int> QtyAfterWast { get; set; }
    }
}
