//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderSummary
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string MaterialName { get; set; }
        public string MaterialGroup { get; set; }
        public string UOM_1 { get; set; }
        public string Type { get; set; }
        public string Capacity_AMH { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public int Qty { get; set; }
        public int Amount { get; set; }
        public string GrossAmount { get; set; }
        public string GrossTotal { get; set; }
        public string Fright { get; set; }
        public string NetAmount { get; set; }
        public string PurchaseId { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Sac { get; set; }
        public Nullable<int> Rate { get; set; }
        public string GstAmount { get; set; }
        public string GstTotal { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> PoType { get; set; }
    }
}
