//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityCheck
    {
        public int Id { get; set; }
        public string BomNo { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Mat1 { get; set; }
        public Nullable<int> Mat2 { get; set; }
        public Nullable<int> Mat3 { get; set; }
        public Nullable<int> Mat4 { get; set; }
        public Nullable<int> Mat5 { get; set; }
        public Nullable<int> Mat6 { get; set; }
        public Nullable<int> Mat7 { get; set; }
        public Nullable<int> Mat8 { get; set; }
        public Nullable<int> Mat9 { get; set; }
        public Nullable<int> Mat10 { get; set; }
        public string ReworkPass { get; set; }
        public string QcPass { get; set; }
        public string QcNo { get; set; }
        public string WipNo { get; set; }
    }
}
