//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTable
    {
        public int Id { get; set; }
        public int Location { get; set; }
        public string WipNo { get; set; }
        public string JobNo { get; set; }
        public string BomNo { get; set; }
        public string ProductCode { get; set; }
        public int Mat1 { get; set; }
        public int Mat2 { get; set; }
        public int Mat3 { get; set; }
        public int Mat4 { get; set; }
        public int Mat5 { get; set; }
        public int Mat6 { get; set; }
        public int Mat7 { get; set; }
        public int Mat8 { get; set; }
        public int Mat9 { get; set; }
        public int Mat10 { get; set; }
        public string QcNo { get; set; }
        public string QcPass { get; set; }
        public string Rework { get; set; }
        public string QcRework { get; set; }
        public string IndivisualPacking { get; set; }
        public string BoxPacking { get; set; }
        public string PGI { get; set; }
        public string ChallanNo { get; set; }
        public string challanDate { get; set; }
        public string CustomerCode { get; set; }
        public string SalesOrderId { get; set; }
        public string ProdSerialNo { get; set; }
    }
}
