//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capitaplus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string MatName { get; set; }
        public string Type { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public int Qty { get; set; }
        public int StanderdConsuption { get; set; }
        public int ActualConsuption { get; set; }
        public int WastQty { get; set; }
        public string WipNo { get; set; }
        public string Date { get; set; }
        public string BomNo { get; set; }
        public string jobNo { get; set; }
        public Nullable<int> QtyAtLocation { get; set; }
    }
}
